### ISSUE TITLE
Code Duplication in Memory Management

### ISSUE THREAD

**Issue by kiplangatkorir** [GraphFusion/GraphFusion-NMN#26]
Redundant code exists between `GraphFusion` and `NeuralMemoryNetwork` classes, particularly in memory management and processing methods.

**Duplicate Functionality**
```
# In GraphFusion
def _update_global_memory(self, current: torch.Tensor, new: torch.Tensor, confidence: float, decay: float = 0.99):
    return current * decay + new * confidence * (1 - decay)

# In NeuralMemoryNetwork
@staticmethod
def _update_global_memory(current: torch.Tensor, new: torch.Tensor, confidence: float, decay: float = 0.99):
    return current * decay + new * confidence * (1 - decay)
```
**Tasks**

- [ ]  Identify all duplicate code
- [ ]  Create shared utilities
- [ ]  Refactor memory management
- [ ]  Update documentation
- [ ]  Add tests for refactored code
